package com.loan_service.enums;

public enum ApplicationStatus {
	DRAFT, SUBMITTED, UNDER_REVIEW, CREDIT_CHECK_PENDING, CREDIT_CHECK_COMPLETED, APPROVED, REJECTED, DOCUMENTS_PENDING,
	DOCUMENTS_VERIFIED, CANCELLED
}
