package com.notification.enums;

public enum NotificationType {
	PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    ACCOUNT_CREDITED,
    ACCOUNT_DEBITED,
    LOW_BALANCE_ALERT,
    CARD_PAYMENT,
    UPI_PAYMENT,
    BILL_PAYMENT,
    SECURITY_ALERT,
    LOGIN_ALERT,
    PASSWORD_CHANGED,
    OTP_VERIFICATION,
    PROMOTIONAL,
    MARKETING,
    SYSTEM_MAINTENANCE,
    ACCOUNT_CREATED,
    ACCOUNT_VERIFIED,
    KYC_APPROVED,
    KYC_REJECTED
}
