package com.user_service.event;

public enum KeycloakEventType {
	VERIFY_EMAIL, UPDATE_EMAIL, UPDATE_PASSWORD, REMOVE_TOTP, UPDATE_TOTP, SEND_VERIFY_EMAIL, SEND_RESET_PASSWORD,
	LOGIN, LOGOUT, REGISTER, DELETE_ACCOUNT
}
