package com.user_service.enums;

public enum AuditAction {
	// User actions
	USER_CREATED, USER_UPDATED, USER_DELETED, USER_ACTIVATED, USER_DEACTIVATED, USER_LOGIN, USER_LOGOUT,

	// Profile actions
	PROFILE_UPDATED, PROFILE_VIEWED,

	// Password actions
	PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,

	// Settings actions
	SETTINGS_UPDATED, NOTIFICATION_PREFERENCES_UPDATED,

	// Admin actions
	ADMIN_ACCESS, CACHE_CLEARED, RATE_LIMIT_RESET,

	// Security actions
	FAILED_LOGIN_ATTEMPT, ACCOUNT_LOCKED, SUSPICIOUS_ACTIVITY
}
