package com.user_service.enums;

public enum AuditAction {

	// Authentication Events
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	LOGOUT,

	// User actions
	USER_CREATED,
	USER_UPDATED,
	USER_DELETED,
	USER_ACTIVATED,
	USER_DEACTIVATED,
	USER_LOGIN,
	USER_LOGOUT,

	// Profile actions
	PROFILE_UPDATED,
	PROFILE_VIEWED,

	// Password actions
	PASSWORD_CHANGED,
	PASSWORD_RESET_REQUESTED,
	PASSWORD_RESET_COMPLETED,
	PASSWORD_RESET_INITIATED,
	PASSWORD_RESET_FAILED, // When reset attempt fails
	PASSWORD_RESET_REVOKED, // When admin revokes reset token
	PASSWORD_VALIDATION_FAILED, // When password doesn't meet requirements

	// Settings actions
	SETTINGS_UPDATED,
	NOTIFICATION_PREFERENCES_UPDATED,

	// Admin actions
	ADMIN_ACCESS,
	CACHE_CLEARED,
	RATE_LIMIT_RESET,

	// Security actions
	FAILED_LOGIN_ATTEMPT,
	ACCOUNT_LOCKED,
	SUSPICIOUS_ACTIVITY,
	RATE_LIMIT_EXCEEDED,
	INVALID_TOKEN_ATTEMPT,
	TOKEN_REUSE_ATTEMPT,

	// Email Events
	VERIFICATION_EMAIL_SENT,
	PASSWORD_RESET_EMAIL_SENT,
	PASSWORD_CHANGED_NOTIFICATION_SENT
}
